name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v2.4.2
        with:
          host: 192.241.153.48
          username: root
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          port: 22
          script: |
            cd /var/family/barber-online
            rm -rf *
            cp -r /home/runner/work/<YOUR-REPO-NAME>/<YOUR-REPO-NAME>/dist/* .
            pm2 reload all
