name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.7
        with:
          REMOTE_HOST: 192.241.153.48
          REMOTE_USER: root
          PASSWORD: mdt1234@
          REMOTE_PORT: 22
          SOURCE: dist/
          TARGET: /var/family/barber-online/
          EXCLUDE: ".git"

      - name: Build
        run: pm2 restart all

      - name: Reload PM2 apps
        uses: appleboy/ssh-action@v0.1.7
        with:
          USERNAME: root
          HOST: 192.241.153.48
          PORT: 22
          PASSWORD: mdt1234@
          SCRIPT: pm2 reload all
