name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_BARBER }}
          SOURCE: "dist/"
          REMOTE_HOST: 192.241.153.48
          REMOTE_USER: root
          TARGET: /var/family/barber-online/
          EXCLUDE: "/dist/, /node_modules/"
