name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: easingthemes/ssh-deploy@v2
        with:
          ssh-private-key: ${{ secrets.DEPLOY_BARBER }}
          remote-host: 192.241.153.48
          remote-user: root
          remote-port: 22
          source: dist/
          target: /var/family/barber-online/
          args: "-rlgoDzvc --delete"
          exclude: ".git"

      - name: Reload PM2 apps
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: 192.241.153.48
          port: 22
          key: ${{ secrets.DEPLOY_BARBER }}
          script: pm2 reload all
