name: Node.js CD

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy [Server PullUp HML DO]
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DEPLOY_BARBER }}
          port: 22
          passphrase: mdt1234@
          script: |
            whoami
            cd /var/www/barber-online
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            nvm use 19.4.0
            git pull
            npm install
            npm run build
            pm2 restart all
