name: CD(continuous deploy)

on:
  push:
    branches:
      - main

jobs:
  pipeline-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Update the application
        uses: appleboy/ssh-action@master
        with:
          host: "mackbarbearia.com.br"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: "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"
          script: |
            cd /var/family/barber-online && 
            git fetch &&
            git checkout ${{ steps.extract_branch.outputs.branch }} &&
            git pull origin ${{ steps.extract_branch.outputs.branch }} && cd /var/family/barber-online &&
            pm2 restart all
