name: CD(continuous deploy)

on:
  push:
    branches:
      - main

jobs:
  pipeline-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Update the application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/family/barber-online && 
            git fetch &&
            git checkout ${{ steps.extract_branch.outputs.branch }} &&
            git pull origin ${{ steps.extract_branch.outputs.branch }} && cd /var/family/barber-online &&
            pm2 restart all
