name: Node.js CD

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Debug SSH Key
        run: echo "$SSH_PRIVATE_KEY"

      - name: SSH Deploy [Server PullUp HML DO]
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          port: 22
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            whoami
            cd /var/www/barber-online
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            nvm use 16
            git pull
            npm install
            npm run build
            pm2 restart barber
